Update setup.py
Hi, @minyoungg . Thanks for the great work. I'd like to point out one issue which may result in CUDA device issue like
```
self._fn_tn(
  File "cupy/_core/raw.pyx", line 93, in cupy._core.raw.RawKernel.__call__
  File "cupy/cuda/function.pyx", line 223, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 205, in cupy.cuda.function._launch
  File "cupy_backends/cuda/api/driver.pyx", line 273, in cupy_backends.cuda.api.driver.launchKernel
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
python-BaseException
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 234, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 234, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 234, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
ERROR conda.cli.main_run:execute(47): `conda run python /home/student2/juntao/.pycharm_helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client localhost --port 44463 --file /home/student2/juntao/MyPycharm/VIBE/VIBE_240107.py` failed. (See above for error)
```

Your install requirements are
```
install_requires=[
            "torch>=1.13.0",
            "string-color==1.2.3",
            "torchpq==0.3.0.1",
    ],
```
in `setup.py`.

However, in `torchpq-0.3.0.1`, there is a bug that they always create new tensors on `cuda:0`, it is a problem for those who have multiple devices. The author of `torchpq` fixed the bug since version 0.3.0.3 (see [link](https://github.com/DeMoriarty/TorchPQ/commit/210059aaa5c4fcaff23de45a56bfdb04064ab691)).

So I suggest you update the install requirements in `setup.py` to 
```
install_requires=[
            "torch>=1.13.0",
            "string-color>=1.2.3",
            "torchpq>=0.3.0.3",
    ],
```

Best,
Chris
:)